dependencies:
  - name: hdfs-config-k8s
    version: "0.1.0"
    repository: "file://../hdfs-config-k8s"
    condition: condition.subchart.config
  - name: hdfs-krb5-k8s
    version: "0.1.0"
    repository: "file://../hdfs-krb5-k8s"
    condition: condition.subchart.kerberos
    tags:
      - kerberos
  - name: hdfs-namenode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-namenode-k8s"
    condition: condition.subchart.namenode
  - name: hdfs-datanode-k8s
    version: "0.1.0"
    repository: "file://../hdfs-datanode-k8s"
    condition: condition.subchart.datanode
  - name: hdfs-client-k8s
    version: "0.1.0"
    repository: "file://../hdfs-client-k8s"
    condition: condition.subchart.client
